// app/layout.tsx
import ChakraProviderWrapper from '../providers/ChakraProvider';

export const metadata = {
  title: 'Nextjs10000',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProviderWrapper>{children}</ChakraProviderWrapper>
      </body>
    </html>
  );
}
